### ISSUE TITLE
Validation and test data is swapped

### ISSUE THREAD

**Issue by alexchen42** [tqbl/gccaps#1]
Thank you for your easy to use repository!

When adjusting the paths to match data on my machine, I noticed you have reversed the path for `validation_set` and `test_set` in `gccaps/config/paths.py`.

Your validation_set points to `groundtruth_strong_label_testing_set.csv` instead of `groundtruth_strong_label_evaluation_set.csv` and vice versa.

So it might be that the results in your paper are using the wrong dataset because of this.

**Comment by tqbl** [comment]
Thank you for the concern, alexchen42.

The code is actually correct. The confusion comes from the fact that the DCASE 2017 datasets call the validation set the 'testing set' and the test set the 'evaluation set'. See: http://www.cs.tut.fi/sgn/arg/dcase2017/challenge/task-large-scale-sound-event-detection.

I wanted to follow the naming that is familiar to the machine learning community, but also retain the metadata file names used by the task organisers. The latter might not have been the best choice in retrospect. I think what I'll do is simply update the documentation to make the naming difference clear.
