### ISSUE TITLE
Training using strong-labeled data

### ISSUE THREAD

**Issue by leanderme** [tqbl/gccaps#2]
Hi, thank you for sharing this!
Have you tried training the network with "strong"-labeled annotation data, i.e. feeding onset and offset information alongside the label into the network? Does the architecture allow this and if so, what changes would be necessary to do this?
Any help is greatly appreciated

**Comment by tqbl** [comment]
Thanks for the interest, leanderme. The architecture as it is cannot learn with strongly labelled data. An intermediate stage of the network computes block-level predictions, but these predictions are then aggregated to give a single prediction.

To train with strong labelled data, you could remove the final aggregation stage. The ground truth labels of the blocks would be based on the onset and offset times, e.g. if (A, 0s, 1s) is a sound event and a block is 100 ms in length, the first 10 blocks should be labelled with class 'A'. To get onset and offset times during inference, you would then do the conversion in the opposite direction. The code for the latter is already available (see inference.py).

In this architecture, the final feature map has shape 30x8x64, so a block, corresponding to a 1x8x64 slice, is ~333 ms in duration. You may want to increase the granularity by not pooling the time dimension or introducing an upsampling stage.
